### ISSUE TITLE
Using a configuration file instead of parsing .lily (garden)

### ISSUE THREAD

**Issue by azbshiri** [jesserayadkins/lily#202]
Hey, I think it's better to read configuration files then call the real functions based on properties instead of parsing .lily file and generating a python literal to evaluate.

**Comment by azbshiri** [comment]
@jesserayadkins

**Comment by jesserayadkins** [comment]
I think it's worth looking into. Though at the moment I'm a bit hesitant to touch anything in Garden because I'm more focused on the core.

**Comment by azbshiri** [comment]
I think I can do that. if the language going to be used by people some of them would not write their stuff in Lily and some of them means a lot ;D however I'm more interested in the language core than garden because I've spent much time to learn C language and other low-level things to be able to write/contribute something like this project. I'd appreciate if you write what part should I start to read/review.

**Comment by jesserayadkins** [comment]
Creating a List.merge function would be the easiest thing to start off with. You'd need to manually adjust the dynaload tables, since I don't have the tooling in place quite yet. I should have it done by the end of next week.

If you can figure out what's causing #203 or #186, that would save me a lot of time.

Once the api is done, then writing packages for networking/subprocess exec would be a step toward making Garden in Lily only.

I love the enthusiasm, but right now the problem is me and the lack of api's/tooling so that you won't get burned by dynaload tables/loaders/etc.

**Comment by azbshiri** [comment]
Is there an issue for List.merge? or I just should create one and send a pull request?

**Comment by jesserayadkins** [comment]
There's nothing listed for it. You can create an issue and a PR, or just a PR.

**Comment by jesserayadkins** [comment]
Now that I've pushed postgres out of the core as of 8cfa3a6, I decided to take a look at what garden is doing. Having seen the configuration file, I agree. A configuration file styled format would be easier to work with. I have a couple of other small changes in mind as well.

The format I have in mind is to start off with simple `x: value` pairs, and then expand from there if eventually necessary.
