### ISSUE TITLE
Conditional operators return Integer?

### ISSUE THREAD

**Issue by stevedonovan** [jesserayadkins/lily#205]
```
scratch$ lily bug.lly
SyntaxError: Argument #2 to List.reject is invalid:
Expected Type: Function (Integer => Boolean)
Received Type: Function (Integer => Integer)
    from bug.lly:2
scratch$ cat bug.lly
var ls = [10,20,30,40]
ls.reject{|x| x == 20 || x == 40} |> print
```

**Comment by jesserayadkins** [comment]
That's a relic from a long time ago. Originally, Lily didn't have Boolean class, so conditionals were done through Integer values. I never got around to fixing it.

If you're looking to contribute, you can probably fix this by going to emitter's and/or handling and using o_get_boolean instead of o_get_integer, and fixing any tests that might break (I doubt that will happen though).

I'm about to go to sleep and, otherwise, I can get to it tomorrow since I'm 99% sure this is super easy.

**Comment by stevedonovan** [comment]
Well, it was easy to fix in `eval_logical_op` - the key was replacing `integer_class` with `boolean_class` in when getting storage.

Now for the not-so-easy part: your basic tests broke, basically because you assume that logical results _are_ integers.  So, how to proceed - shall I make tests work with strict comparisons? Or is there some deeper thinking to be done?

```
ok({||
    var a = 1, b = 2, c = 3
    a = b = c
    var result = ((a == 3 && b == 3))
    result == 1}(),                       "Basic assignment chain.")   # becomes 'result == true' etc
```

**Comment by stevedonovan** [comment]
Basically, with those few changes, all the pass tests pass. Shall I do up a PR?

**Comment by stevedonovan** [comment]
The rot lies deeper, I think

```
print("2343".is_digit() == true)
==> false
```
which is because is_digit returns an integer, which I can see from the implementation.

**Comment by jesserayadkins** [comment]
That's a definite bug then. Same issue again: `String.is_digit` was made before Boolean was added on, and I missed some conversions from Integer to Boolean.

But if you can fix it, a PR would be gladly accepted.

**Comment by stevedonovan** [comment]
Cool, all tests fine here with mingw...now I'll submit the and/or PR

**Comment by jesserayadkins** [comment]
Whoops, forgot to close this when I did the merge.
