### ISSUE TITLE
Loading postgres.so

### ISSUE THREAD

**Issue by stevedonovan** [jesserayadkins/lily#221]
I  note that postgres.so is installed as /usr/local/lib/lily/0_16/postgres.so.  The tutorial should be updated to reflect that this is the location for 'system' modules?  I was confused because trying my little test app in the `libs` dir led to a most puzzling 'postgres.so not found', even though it was there!

At first it just failed, so I modified to use `PQconnectdb` if there's only one argument, et voila, things worked. It's probably my misunderstandings about the more complete way to create a connection. It _would_ be useful to return `Either[Conn,String]` so we can see the mysterious errors that Postgres puts out.

`Conn.query` is cool, but should probably expose `PQescapeLiteral` so that SQL injection attacks aren't pitifully easy.

I'll now go back to finishing some of my own projects, and let you do some thinking in peace.

**Comment by stevedonovan** [comment]
Seems there's a glitch - I have my test script in lib, but can only run it from ../lib

```
lily$ ls lib
liblily.a  postgres.so  test.lly
lily$ cat lib/test.lly
import postgres
var conn = postgres.Conn.open("dbname = pas")
if conn.is_none(): {
   print("borked")
else: 
   var c = conn.unwrap()
   match c.query("select count(*) from sessions"): {
   case Right(res):
      res.each_row {|row| print(row) }
   case Left(s):
      print(s)
   }
}
lily$ lily lib/test.lly
["200"]
```
But I can't run `lily test.lly` in lib itself. Appears to the /usr/local/lib/lly... was a red herring, since it isn't available globally.

**Comment by stevedonovan** [comment]
OK, found the glitch - when `dlopen` is called with a filename without a path, it looks in the system lib path (the Windows equivalent doesn't work like this).  So if I copy `postgres.so` to `/usr/lib` then `import postgres` works from anywhere in the system. Not sure what the best resolution is, because it's OS-specific.

**Comment by jesserayadkins** [comment]
Hmm...postgres really shouldn't be installing itself. It's meant to be loaded as a package through Garden. But postgres can't quite be pushed out of the core yet, because it still relies on a few parts that are not yet in api.

**Comment by stevedonovan** [comment]
Ah! How Lua resolves this problem is quite simple; you would have a 'path' like "./?.so; /usr/local/lib/lily/0_16/?.so" and take each in turn, substituting the module name for '?'. The first one that exists wins. The take home really is that always pass a path to dynamic library loaders, not just a filename. It's a flexible system because this is a table field `package.cpath` and it can be modified by the program.

**Comment by jesserayadkins** [comment]
I tried Lua's approach for a while, but I eventually switched away from it. I like that I can have Garden install some repository onto a package, and not worry about some other package breaking because 1.0 doesn't work with 1.1, for example. Packaging means that I can effectively drag and drop libraries over. So I'll look later on into fixing that (because library loading should always be relative if loading as a module).

**Comment by stevedonovan** [comment]
That makes sense. Package management is hard - my connection Hisham goes LuaRocks and it becomes a real hard act when multiple versions of the language co-exist.

**Comment by jesserayadkins** [comment]
As of 8cfa3a6, I've pushed postgres into a repository by itself, and while I was at it, I also dropped it installing to a particular directory. It seems that there are a few other issues inside of this one:

One, that import should absolutely not be doing that. Possibly an easy fix.

Two, about `Conn.open` pushing an `Either` back instead of an `Option`. I agree (especially because there's a 5-`String` constructor, and thus easy to get it wrong.

Three, that `PQescapeLiteral` should be wrapped. That one, I need some time to think of how I want to do it.

I'll take a swing at the first two, and close this when they're done. For the third, I'll open an issue on the postgres repo once I've gotten to settling the packaging and documentation.
