### ISSUE TITLE
Option method next

### ISSUE THREAD

**Issue by stevedonovan** [jesserayadkins/lily#226]
Existing `Option` methods are meant for chaining, which is cool. But sometimes we just want to do something on a value, and having to return `None` from `and_then` feels awkward.

```C
"42".parse_i().and_then{|n|
   print($"answer is ^(n)")
   None
}
```
So `Option.then[A, B](self, fn: Function(A)` seems useful.

**Comment by jesserayadkins** [comment]
Something I want to do (but haven't filed an issue for yet) is to add a Unit type to Lily. That is, all functions implicitly return Unit (which is some empty value) when they don't have an explicit return.

In your above example, there would be no need for a `then`, as with a Unit type `and_then` would push back `Option[Unit]`.

**Comment by jesserayadkins** [comment]
To add to that, Unit solves two lagging problems

#127, you can write doc as a method on any function (`Function(~1):Unit)`).

#187, you can write dis.dis using the same signature: It takes one argument of `Function(~1):Unit` which thus covers every `Function` that could possibly be created because Unit is a bottom type.

**Comment by stevedonovan** [comment]
That's an elegant solution. Any sacrifice in type safety?

**Comment by alpha123** [comment]
@stevedonovan Nope, lots of type-safe languages have a void/unit type (Haskell, ML‚ etc).

**Comment by jesserayadkins** [comment]
I've opened #231 to address the need for a Unit type, so I'll be closing this.
