### ISSUE TITLE
"Traceback:" not on a new line for some custom exception messages.

### ISSUE THREAD

**Issue by a-p-** [jesserayadkins/lily#253]
The "Traceback:" part of the uncaught exception output can blend into the custom exception message (if the message doesn't end with a newline character):

    $ ./lily -s 'raise Exception("test")'
    Exception: testTraceback:
        from [cli]:1: in __main__
    $ 

rather than being on a new line like in other cases:

    $ ./lily -s '1/0'
    DivisionByZeroError: Attempt to divide by zero.
    Traceback:
        from [cli]:1: in __main__
    $ 

(With a build of: 11a03d11b6cb06562e00e4d5d139408c93de63cf)

**Comment by jesserayadkins** [comment]
Right now, all exception messages have a hardcoded newline at the end of them, because the traceback printer doesn't print a newline in between the exception message and the rest of the traceback. It's one of those debt issues that I've yet to tackle. I can drum up a fix later, but it'll take some time since I need to comb through the strings.
