### ISSUE TITLE
Possibly-incorrect error message: "SyntaxError: Attempt to use uninitialized value 'b'."

### ISSUE THREAD

**Issue by a-p-** [jesserayadkins/lily#259]
For code like this:

    var a = 123
    var b = 890
    (a) = b

lily (4973a917612c85f24be2f852af2f75f0f2722cad) gives an error message like:

    $ ../build/lily test.lly 
    SyntaxError: Attempt to use uninitialized value 'b'.
        from test.lly:3
    $ 

Seems like the error message might be wrong, since `b` was initialized to a constant in line 2?

**Comment by jesserayadkins** [comment]
The interpreter doesn't have semicolons, and it doesn't break statements up by newlines either (otherwise function piping would break in some cases).

So what you're writing is seen like this:

```
var a = 123
var b = 890(a) = b
```

The second line is thus seen as a broken assignment chain wherein you're calling a constant with 'a', and 'b' is being assigned to that. Assign chains run right-to-left, thus causing this seemingly odd message.

If the last line is rewritten as `a = b`, then the code works.

**Comment by stevedonovan** [comment]
Yes, there's no way this could be unambiguous syntax (say b was set to a
function value, then (b) would try to call it).

But it _suggests_ tuple-unpacking;  var (x,y) = call_returning_tuple_2()

This could be rather useful.

**Comment by jesserayadkins** [comment]
Tuple unpacking has uses, and I think it's easy enough that I wouldn't mind putting it in. But if I were to do that, I would want to wait a while so I can think of what corner cases might pop up for it.

**Comment by stevedonovan** [comment]
On Fri, Jul 15, 2016 at 10:57 AM, Jesse Ray Adkins <notifications@github.com
> wrote:
Tuple unpacking has uses, and I think it's easy enough that I wouldn't mind
putting it in. But if I were to do that, I would want to wait a while so I
can think of what corner cases might pop up for it.

The syntax seems unambiguous - can't think of how an _expression_ can
otherwise occur after var. The new C++ syntax is 'auto [x,y] =...' which is
another alternative.  The matching rules would be as strict as possible, of
course. The thing to avoid is Python-style automagic.

**Comment by jesserayadkins** [comment]
I'd like to let it sit in my mind for a bit, in case I get any ideas about the direction that I want to go with the syntax. There are some lingering questions, like should existing vars be allowed to participate? What about creating properties versus creating normal vars versus global vars. That's less about affecting this, and more about the implementation being a little tricky there.

But that's for another time. For now, I'm closing this since I don't think there's a bug here.
