### ISSUE TITLE
Problem with postgres module

### ISSUE THREAD

**Issue by stevedonovan** [jesserayadkins/lily#263]
It got pulled nicely using Garden, but the build is borked because it cannot find the postgres client header file. Your CMakeLists.txt file references the header file before you look for PQ.  It might work fine on other systems, but in Ubuntu that file ends up in /usr/include/postgres.

(I'm still a bit vague on where package .so must live to be globally available to Lily.)

**Comment by jesserayadkins** [comment]
Sorry about that. Pushed a fix just now. As for what to do with the .so, you don't need to do anything. You garden install, then add a `use postgres` is a script that's in the same directory as the packages directory. There's no truly globally available library base, as in say Lua or Python.

**Comment by stevedonovan** [comment]
I think that's a fine approach, as long as a symlink to that application results in the same package directory being seen.  For that I suspect you'll need a build option to directly wire the exe location into Lily (it's a hard problem in general to find out where your exe lives) so that such an application can be _accessed_ globally.

**Comment by stevedonovan** [comment]
(It's something I do with my luabuild project - a tool for building customized Lua exes with their location embedded so that they can have completely self-contained packages)

**Comment by jesserayadkins** [comment]
I think I understand what you're getting at. As far as trying to make a self-contained exe, having a pluggable loader (as in, farming out the "I have a path, and I want a thing"), might go toward solving that problem. Flatten the directory, make a custom loader that transforms flattened paths so that the Lily interpreter doesn't know the difference.

I'll admit that I'm in the dark on the subject. Later on, I'll take a look at what you've done. One of the targets for Lily is game dev, and so being able to ship a single exe (or at least flattening paths and code) will be important later on.

**Comment by stevedonovan** [comment]
It's good to think about these things upfront. The usual Python/Lua scheme is clunky when you want to release a self-contained executable, since by default extensions end up all over the filesystem. The custom loader idea is a good one.

**Comment by stevedonovan** [comment]
Not quite there yet ;) You put the `find_package(PQ)` before the `set(CMAKE_MODULEPATH...)` statement. cmake then complains that it cannot find the PQ package. For some reason, this matters. (I'm not an expert on this cmake thing). Another thing: I note you define CID_CONN and CID_RESULT but use CID_CONN for _both_ classes. A few words on how the `cid_table` works would be appreciated!

**Comment by jesserayadkins** [comment]
The cid table is there so that foreign structs can get the right ids. Those ids are used by the vm to print the name of the class, and if you try to cast a value away from a Dynamic.

Try it now.

**Comment by stevedonovan** [comment]
Ah thanks, works perfectly from scratch now.

A somewhat off-topic question, what signature to use for functions with a multiple number of values of different types? Doesn't make that much sense for a Lily function, but I'd like to try a variant of Python's `format` function. That is, make the type checker relax a little and let me iterate over lily_value args in C.

**Comment by jesserayadkins** [comment]
Good! As for the second part...

I know what you're asking for, and I have something right now that works for `Tuple` (it's the `1` type). It's a weird type that accepts any argument, but keeps a memory of what it's seen. I don't know if it'll work for variable arguments though, or at all. I've seriously not tested it at all. It's currently hardcoded to only work for `Tuple`, so you may have trouble extending it.

At the moment, it's not going to work without giving ts a few gentle nudges so that it can understand `1` as a normal argument.

**Comment by stevedonovan** [comment]
It's a small thing, of use only to module writers I suppose.  Yes, I've seen that weird `Tuple[1]` in the library code, which intrigued me.  C++ has variadic templates but they still give me headaches, other than the straightforward recursive use to define a mult-argument type-safe `print` function.

**Comment by jesserayadkins** [comment]
I pushed a commit to allow `1` to be matched directly. I've been meaning to do that, because this opens the door to a `List.zip` that handles any number of secondary lists (which is awesome, btw). Hopefully, you should be able to accomplish what you're trying to do with a signature that finishes off with `1...`.

**Comment by stevedonovan** [comment]
With signature `define print (1...): Integer` I get this crash when trying to print out a type mismatch error:
```
#1  0x0000000000424940 in lily_mb_add_fmt_va (msgbuf=0x6432a0, 
    fmt=0x436f18 "Argument #%d to %s%s%s is invalid:\nExpected Type: ^T\nReceived Type: ^T", var_args=0x7fffffffdac8)
    at /home/steve/projects/scratch/dev/lily/src/lily_msgbuf.c:356
356	                add_type(msgbuf, type);
(gdb) l
351	
352	            i++;
353	            c = fmt[i];
354	            if (c == 'T') {
355	                lily_type *type = va_arg(var_args, lily_type *);
356	                add_type(msgbuf, type);
357	            }
358	            else if (c == 'I') {
359	                int indent = va_arg(var_args, int);
360	                msgbuf_add_indent(msgbuf, indent);
(gdb) p type
$1 = (lily_type *) 0x31
```
That's definitely not a pointer ;)

**Comment by stevedonovan** [comment]
Scrub that - forgot to INSTALL first ;)  No more crashes!

**Comment by stevedonovan** [comment]
Works like a bomb - as they say this side of the Atlantic, i.e. it did NOT bomb ;)

```c
/**
define print (1...)

Print several values
*/
void lily_xstr__print(lily_vm_state *vm, uint16_t argc, uint16_t *code)
{
   lily_list_val *lv = lily_arg_list(vm,0);
   lily_msgbuf *msgbuf = lily_vm_msgbuf(vm);
   int i;
   lily_mb_flush(msgbuf);
   for (i = 0; i < lily_list_num_values(lv); i++) {
      lily_value *v = lily_list_value(lv,i);
      if (i > 0)
         lily_mb_add_char(msgbuf,'\t');
      lily_vm_add_value_to_msgbuf(vm, msgbuf, v);
   }
   lily_mb_add_char(msgbuf,'\n');
   fputs(lily_mb_get(msgbuf),stdout);
   lily_mb_flush(msgbuf);
}
```
That function `lily_vm_add_value_to_msgbuf` - is it part of the official public API?

**Comment by jesserayadkins** [comment]
Not yet, but it's close enough to it. I've been wanting to pull that into msgbuf under `lily_mb_add_value` in the order of mb, vm, and value. For now, it effectively is and it's safe to use (it can't throw).
