### ISSUE TITLE
Strange segfault when using each()

### ISSUE THREAD

**Issue by stevedonovan** [jesserayadkins/lily#265]
I've managed to get this one down to a few lines:

```python
import dis

define generate_prototype_test {
    var ss = 1
    var parms = [""]
    var args = ["bob"]
    for idx in 0...0: {
        var a = args[idx]
        stderr.print(a)
        parms.each{|p|  ss += 1 }
    }
}

generate_prototype_test()
#print(dis.dis(generate_prototype_test))
```
The conditions for the segfault seem to be:
  - in a loop
  - each() modifies a variable in enclosing scope
  - taking away that debug print causes problem to go away ;)

Here is the dissembly:
```
[0-3] (58) o_create_closure
    [   1] line:    3
    [   2] size:    1
    [   3] ======>  #13

[4-7] (42) o_get_integer
    [   5] line:    4
    [   6] value:   1
    [   7] ======>  #0

[8-11] (57) o_set_upvalue
    [   9] line:    3
    [  10] <------  #0 (up)
    [  11] <------  #0

[12-15] (41) o_get_readonly
    [  13] line:    5
    [  14] literal: 2
    [  15] ======>  #3

[16-20] (33) o_build_list
    [  17] line:    5
    [  18] count:   1
    [  19] <------  #3
    [  20] ======>  #2

[21-24] (41) o_get_readonly
    [  22] line:    6
    [  23] literal: 3
    [  24] ======>  #3

[25-29] (33) o_build_list
    [  26] line:    6
    [  27] count:   1
    [  28] <------  #3
    [  29] ======>  #5

[30-33] (42) o_get_integer
    [  31] line:    7
    [  32] value:   0
    [  33] ======>  #1

[34-37] (0) o_fast_assign
    [  35] line:    7
    [  36] <------  #1
    [  37] ======>  #7

[38-41] (42) o_get_integer
    [  39] line:    7
    [  40] value:   0
    [  41] ======>  #1

[42-45] (0) o_fast_assign
    [  43] line:    7
    [  44] <------  #1
    [  45] ======>  #8

[46-49] (42) o_get_integer
    [  47] line:    7
    [  48] value:   1
    [  49] ======>  #9

[50-55] (27) o_for_setup
    [  51] line:    7
    [  52] <------  #7
    [  53] <------  #8
    [  54] <------  #9
    [  55] ======>  #6

[56-62] (26) o_integer_for
    [  57] line:    7
    [  58] <------  #7
    [  59] <------  #8
    [  60] <------  #9
    [  61] ======>  #6
    [  62] +>    |  [96]

[63-67] (37) o_get_item
    [  64] line:    8
    [  65] <------  #5
    [  66] <------  #6
    [  67] ======>  #10

[68-71] (39) o_get_global
    [  69] line:    9
    [  70] ======>  #0 (G)
    [  71] ======>  #11

[72-78] (28) o_foreign_call
    [  73] line:    9
    [  74] func:    4
    [  75] count:   2
    [  76] ======>  #0
    [  77] <------  #11
    [  78] <------  #10

[79-82] (57) o_set_upvalue
    [  80] line:    3
    [  81] <------  #0 (up)
    [  82] <------  #0

[83-86] (59) o_create_function
    [  85] literal: 6
    [  86] ======>  #12

[87-93] (28) o_foreign_call
    [  88] line:    10
    [  89] func:    5
    [  90] count:   2
    [  91] ======>  #4
    [  92] <------  #2
    [  93] <------  #12

[94-95] (24) o_jump
    [  95] +>    |  [65596]

[96-97] (32) o_return_noval
    [  97] line:    15

```

**Comment by jesserayadkins** [comment]
I believe I've figured this out, but it will be a while before I can get to it. It's quite tricky to fix.

So the way that loops work is that their end is a jump back up. Let's say that the loop end originally had -20.

But then there's a closure. That's going to inject some code. So that -20 isn't going to be correct any longer.

The problem is tricky because that -20 needs to be increased by whatever the increase is between where it was targeting, and where it stopped at. So if there are 2 o_*_upvalue writes in between, then the -20 should be rewritten as -28.

The trouble is making sure that the increases are lined up, and also with doing the increases.

**Comment by stevedonovan** [comment]
Would it not be a better strategy to keep the original position of the jump target, and simply recalculate the jump offset after insertion?

**Comment by jesserayadkins** [comment]
Possibly. I'm currently using a single-pass transformation to fix everything in-place. So I don't know if the information to recalculate would be there by the time that I've done the jump insertion. I may rewrite the transform to use multiple stages, so that I can have one stage get all of the jump targets at once. The second stage can then record jumps and as it goes along write down where opcodes have ended up after their transformation. A third stage can take jumps (which would have their original target), and patch them in-place to their new destination.

The current single-pass strategy has troubles with it being quite difficult to fix jumps.

**Comment by jesserayadkins** [comment]
I also noticed that dis was rendering jump locations wrong, so I pushed a fix for that a while ago too.
