### ISSUE TITLE
Strange issue - codegen?

### ISSUE THREAD

**Issue by stevedonovan** [jesserayadkins/lily#268]
Consider the following:
```python
define parse_line(line: String) {
   var i = -1
   var ch = "X"
   var short = ""
   define get: String {
      i = i + 1
      ch = line[i]
      return ch
   }
   get()
   if ch == "-": {
      if get() == "-": {
      else:
         #var c = ch
         short = ch
      }
   }
   print(short)
}

parse_line("-o whatever")
=> -
```
Uncomment the apparently useless line 'var c = ch' and we get 'o' as expected! Not relying on the return value of `get` - i.e. calling it and _then_ using `ch` - also eliminates the problem.

**Comment by jesserayadkins** [comment]
Strange indeed. I think that, in a roundabout way, this is being caused by functions assuming their output is valid, and always trying to transform it. dis shows that there are three upvalues being loaded at the top, but `short` is not an upvalue (`i` isn't either). I suspect that desync is what's causing the values to come out wrong.
